Global IMessage As String
Global ParentNotify As Integer
Global MDIClient As Integer

Global IMList1(1 To 60) As String
Global IMList2(1 To 60) As String

Global thiswin22 As Integer

Global IMSender1 As String
Global IMSender As String

Declare Function SendMessage Lib "User" (ByVal hWnd As Integer, ByVal wMsg As Integer, ByVal wParam As Integer, lParam As Any) As Long
Declare Function VBEnumChildWindows% Lib "ole01.dll" (ByVal win%, ByVal iNum%)

Global Ignore1 As String
Global Ignore2 As String
Global Ignore3 As String
Global Ignore4 As String
Global Ignore5 As String
Global Ignore6 As String
Global Ignore7 As String
Global Ignore8 As String
Global Ignore9 As String
Global Ignore10 As String
Global Ignore11 As String
Global Ignore12 As String
Global Ignore13 As String
Global Ignore14 As String
Global Ignore15 As String
Global Ignore16 As String
Global Ignore17 As String
Global Ignore18 As String
Global Ignore19 As String
Global Ignore20 As String

Global IM1 As String
Global IM2 As String
Global IM3 As String
Global IM4 As String
Global IM5 As String
Global IM6 As String
Global IM7 As String
Global IM8 As String
Global IM9 As String
Global IM10 As String
Global IM11 As String
Global IM12 As String
Global IM13 As String
Global IM14 As String
Global IM15 As String
Global IM16 As String
Global IM17 As String
Global IM19 As String
Global IM20 As String
Global IM21 As String
Global IM22 As String
Global IM23 As String
Global IM24 As String
Global IM25 As String
Global IM26 As String
Global IM27 As String
Global IM28 As String
Global IM29 As String
Global IM30 As String
Global IM31 As String
Global IM32 As String




